### ISSUE TITLE
AttributeError when calling set_trace() on Python 3.5

### ISSUE THREAD

**Issue by sametmax** [romanvm/python-web-pdb#4]
```
$ python test.py     
Web-PDB: starting web-server on laptop:5555...
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import web_pdb; web_pdb.set_trace()
  File "/home/user/.local/share/virtualenvs/test/lib/python3.5/site-packages/web_pdb/__init__.py", line 209, in set_trace
    pdb = WebPdb(host, port, patch_stdstreams)
  File "/home/user/.local/share/virtualenvs/test/lib/python3.5/site-packages/web_pdb/__init__.py", line 70, in __init__
    Pdb.__init__(self, stdin=self.console, stdout=self.console)
  File "/home/user/.local/share/virtualenvs/test/lib/python3.5/site-packages/pdb.py", line 215, in __init__
    self.stdout = self.ensure_file_can_write_unicode(self.stdout)
  File "/home/user/.local/share/virtualenvs/test/lib/python3.5/site-packages/pdb.py", line 219, in ensure_file_can_write_unicode
    if not hasattr(f, 'stream') and f.encoding and f.encoding.lower() != 'utf-8':
AttributeError: 'WebConsole' object has no attribute 'encoding'
```
This is Python 3.5.1 64 bit on Ubuntu 16.04 in a virtualenv in a file with a simple for loop, started in a ZSH shell.
This is with P

**Comment by romanvm** [comment]
Are you sure you are using the standard CPython 3.5? Because I can't find the line in question in the Standard Library's `pdb.py`. And CI tests would have caught something that trivial as missing attributes.

**Comment by romanvm** [comment]
Quick googling showed that most probably you are using [pdb++](https://bitbucket.org/perkolasoft/pdb) instead of the Standard PDB. Web-PDB works only with PDB from the standard library.

**Comment by sametmax** [comment]
I just tested it and you were right.
