### ISSUE TITLE
Can it support ironpython？

### ISSUE THREAD

**Issue by kweszx** [romanvm/python-web-pdb#9]
**I want to use this tool under ironpython(https://github.com/IronLanguages/ironpython2). but it seems cannot support. Will It can support in the future?**

2018-07-12 17:53:35,422: root - web_console:109 - CRITICAL - Web-PDB: starting web-server on weston-x270:5555...
Traceback (most recent call last):
  File "D:\IronPython.2.7.8\Lib\wsgiref\handlers.py", line 86, in run
    self.finish_response()
  File "D:\IronPython.2.7.8\Lib\wsgiref\handlers.py", line 128, in finish_response
    self.write(data)
  File "D:\IronPython.2.7.8\Lib\wsgiref\handlers.py", line 212, in write
    self.send_headers()
  File "D:\IronPython.2.7.8\Lib\wsgiref\handlers.py", line 270, in send_headers
    self.send_preamble()
  File "D:\IronPython.2.7.8\Lib\wsgiref\handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "D:\IronPython.2.7.8\Lib\wsgiref\handlers.py", line 391, in _write
    self.stdout.write(data)
  File "D:\IronPython.2.7.8\Lib\socket.py", line 328, in write
    self.flush()
  File "D:\IronPython.2.7.8\Lib\socket.py", line 304, in flush
    view = memoryview(data)
TypeError: expected IBufferProtocol, got str
2018-07-12 17:53:55,145: asyncore_wsgi - __init__:167 - ERROR - Exception in <asyncore_wsgi.AsyncWsgiHandler connected 127.0.0.1:22526 at 0x9f>!
Traceback (most recent call last):
  File "D:\IronPython.2.7.8\Lib\site-packages\asyncore_wsgi\__init__.py", line 152, in handle_write
    handler.run(self.server.get_app())
  File "D:\IronPython.2.7.8\Lib\wsgiref\handlers.py", line 92, in run
    self.close()
  File "D:\IronPython.2.7.8\Lib\wsgiref\simple_server.py", line 32, in close
    self.request_handler.log_request(
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by romanvm** [comment]
I don't know anything about IronPython.
